FROM mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim AS base
WORKDIR /app


FROM base AS build
WORKDIR /src
COPY ["Secretary.TelegramBot/Secretary.TelegramBot.csproj", "Secretary.TelegramBot/Secretary.TelegramBot.csproj"]
RUN dotnet restore "Secretary.TelegramBot/Secretary.TelegramBot.csproj"
COPY . .
WORKDIR /src/Secretary.TelegramBot
RUN dotnet build "Secretary.TelegramBot.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Secretary.TelegramBot.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:6.0-bullseye-slim AS final
WORKDIR /app

COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "Secretary.TelegramBot.dll"]